parse_config:
  layer_legend_map:
    {
      "Default": "DEF",
      "Norwegian": "NOR",
      "Number": "NUM",
      "Symbol": "SYM",
      "Navigation": "NAV",
      "Function": "FN",
      "Media": "MED",
      "Adjust": "ADJ",
    }
  raw_binding_map:
    {
      "___X___": { type: dead },
      "KC_NO": { type: dead },
      "XXXXXXX": { type: dead },
      "KC_QUOT": { t: "'", s: '"' },
      "KC_COMM": { t: ",", s: "<" },
      "KC_DOT": { t: ".", s: ">" },
      "KC_SLSH": { t: "/", s: "?" },
      "KC_MINS": { t: "-", s: "_" },
      "KC_TAB": { t: $$mdi:keyboard-tab$$ },
      "HRM_A": { h: Alt, t: A },
      "HRM_S": { h: $$mdi:apple-keyboard-command$$, t: S },
      "HRM_D": { h: SYM, tap: D, type: layer-activator },
      "HRM_F": { h: Shift, t: F },
      "HRM_J": { h: Shift, t: J },
      "HRM_K": { h: SYM, t: K, type: layer-activator },
      "HRM_L": { h: $$mdi:apple-keyboard-command$$, t: L },
      "HRM_SCN": { h: Alt, t: ;, s: ":" },
      "OSL_FUNC": { h: FN, t: FN, type: layer-activator },
      "MED_Z": { h: MED, t: Z, type: layer-activator },
      "MEH_V": { h: MEH, t: V },
      "KC_ESC": ESC,
      "BTN_BS": { h: NAV, t: $$mdi:backspace-outline$$, type: layer-activator },
      "SYM_MINS": { h: SYM, t: "-", s: "_", type: layer-activator },
      "KC_SPC": $$mdi:keyboard-space$$,
      "KC_ENT": $$mdi:keyboard-return$$,
      "KC_BSPC": $$mdi:backspace-outline$$,
      "NO_AA": "Å",
      "NO_OSTR": "Ø",
      "NO_AE": "Æ",
      "QK_REP": "REP",
      "SFT_G": "⇧G",
      "ARRFAT": "=>",
      "ARRSLI": "->",
      "KC_MPLY": $$mdi:play$$,
      "KC_MPRV": $$mdi:skip-previous$$,
      "KC_MNXT": $$mdi:skip-next$$,
      "KC_VOLD": $$mdi:volume-minus$$,
      "KC_MUTE": $$mdi:volume-mute$$,
      "KC_VOLU": $$mdi:volume-plus$$,
      "KC_UP": $$mdi:arrow-up-thin$$,
      "KC_DOWN": $$mdi:arrow-down-thin$$,
      "KC_LEFT": $$mdi:arrow-left-thin$$,
      "KC_RGHT": $$mdi:arrow-right-thin$$,
    }
