combos:
  - { p: [14, 15], k: "{", l: ["Default"] }
  - { p: [15, 16], k: "(", l: ["Default"] }
  - { p: [19, 20], k: ")", l: ["Default"] }
  - { p: [20, 21], k: "}", l: ["Default"] }
  # - { p: [26, 27], k: "<", l: ["Default"] }
  - { p: [27, 28], k: "[", l: ["Default"] }
  - { p: [31, 32], k: "]", l: ["Default"] }
  # - { p: [32, 33], k: ">", l: ["Default"] }
  # - { p: [27, 32], k: "CW", a: bottom, l: ["Default"], offset: 2.5 }
  - { p: [3, 16], k: "CW", l: ["Default"] }
  - {
      p: [38, 39],
      k: "NW",
      a: top,
      offset: 0.5,
      l: ["Default"],
      type: layer-activator,
    }
draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30
  combo_w: 28
  combo_h: 26
  key_rx: 6
  key_ry: 6
  dark_mode: false # Or "auto"
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2
  inner_pad_h: 2
  outer_pad_w: 0
  outer_pad_h: 20
  line_spacing: 1.2
  arc_radius: 6
  append_colon_to_layer_header: false
  small_pad: 2
  shrink_wide_legends: 4
  glyph_tap_size: 20
