parse_config:
  layer_legend_map:
    {
      "Default": "DEF",
      "Norwegian": "NOR",
      "Number": "NUM",
      "Symbol": "SYM",
      "Navigation": "NAV",
      "Function": "FN",
      "Media": "MED",
      "Adjust": "ADJ",
    }
  raw_binding_map:
    {
      "___X___": { type: dead },
      "KC_NO": { type: dead },
      "XXXXXXX": { type: dead },
      "KC_QUOT": { t: "'", s: '"' },
      "KC_COMM": { t: ",", s: "<" },
      "KC_DOT": { t: ".", s: ">" },
      "KC_SLSH": { t: "/", s: "?" },
      "HRM_A": { h: Alt, t: A },
      "HRM_S": { h: $$mdi:apple-keyboard-command$$, t: S },
      "HRM_D": { h: SYM, tap: D, type: layer-activator },
      "HRM_F": { h: Shift, t: F },
      "HRM_J": { h: Shift, t: J },
      "HRM_K": { h: SYM, t: K },
      "HRM_L": { h: $$mdi:apple-keyboard-command$$, t: L },
      "HRM_SCN": { h: Alt, t: ;, s: ":" },
      "OSL_FUNC": { h: FN, t: OSL },
      "MED_Z": { h: MED, t: Z },
      "MEH_V": { h: MEH, t: V },
      "KC_ESC": $$mdi:keyboard-esc$$,
      "BTN_BS": { h: NAV, t: $$mdi:backspace-outline$$ },
      "KC_SPC": $$mdi:keyboard-space$$,
      "KC_ENT": $$mdi:keyboard-return$$,
      "KC_BSPC": $$mdi:backspace-outline$$,
      "NO_AA": "Å",
      "NO_OSTR": "Ø",
      "NO_AE": "Æ",
      "QK_REP": "REP",
      "SFT_G": "⇧G",
      "ARRFAT": "=>",
      "ARRSLI": "->",
    }
