layout:
  layout_name: LAYOUT_split_3x6_3
layers:
  Default: []
  Norwegian: []
  Number:
    - key: 38
      options: { type: held, t: $$mdi:keyboard-space$$, h: CANCEL }
    - key: 39
      options:
        type: held
  Symbol:
    - key: 15
      options:
        type: held
    - key: 20
      options:
        type: held
  Navigation:
    - key: 37
      options:
        type: held
  Function:
    - key: 24
      options:
        type: held
  Media:
    - key: 25
      options:
        type: held
  Adjust:
    - key: 40
      options:
        type: held
