name: Notify Keymap changed

on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/crkbd/keymaps/lorentzfb/drawing/latest/*.svg"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          BASE="https://github.com/lorentzfb/qmk_userspace/blob/$GITHUB_SHA/keyboards/crkbd/keymaps/lorentzfb"
          KEYMAP_SVG_URL="$BASE/drawing/latest/keymap.svg"
          KEYMAP_SOURCE_URL="$BASE/keymap.c"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TASTATUR }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lorentzfb/tastatur/actions/workflows/keymap-changed.yaml/dispatches \
            --data-raw '
            {
              "ref": "main",
              "inputs": {
                "git_sha": "$GITHUB_SHA"
                "keymap_svg_url": "$KEYMAP_SVG_URL",
                "keymap_source_url": "$KEYMAP_SOURCE_URL"
              }
            }'
