name: Notify Keymap changed

on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/crkbd/keymaps/lorentzfb/drawing/latest/*.svg"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TASTATUR }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lorentzfb/tastatur/actions/workflows/keymap-changed.yaml/dispatches \
            -d '{"ref":"main","inputs":{"name":"world"}}'
