name: Notify Keymap changed

on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/crkbd/keymaps/lorentzfb/drawing/latest/*.svg"

env:
  KEYMAP_BASE_DIR: "https://github.com/lorentzfb/qmk_userspace/blob/${{ github.sha }}/keyboards/crkbd/keymaps/lorentzfb"
  KEYMAP_SVG_FILE: "drawing/latest/crkbd_rev1_lorentzfb.svg"
  KEYMAP_SOURCE_FILE: "keymap.c"
  APP_WORKFLOW_URL: "https://api.github.com/repos/lorentzfb/tastatur/actions/workflows/build-deploy.yaml/dispatches"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TASTATUR }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $APP_WORKFLOW_URL \
            --data @- << EOF
          {
            "ref": "main",
            "inputs": {
              "keymap_git_sha": "$GITHUB_SHA",
              "keymap_svg_url": "$KEYMAP_BASE_DIR/$KEYMAP_SVG_FILE",
              "keymap_source_url": "$KEYMAP_BASE_DIR/$KEYMAP_SOURCE_FILE"
            }
          }
          EOF
